### ISSUE TITLE
Organization Config is now breaking

### ISSUE THREAD

**Issue by galenandrew** [dialexa/eslint-config-dialexa#8]
```
Cannot find module '@dialexa/eslint-config-dialexa/node-es6' from '/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules'
Referenced from: /Users/galenandrew/dialexa/cox/vehicle-maintenance/api/.eslintrc
Error: Cannot find module '@dialexa/eslint-config-dialexa/node-es6' from '/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules'
Referenced from: /Users/galenandrew/dialexa/cox/vehicle-maintenance/api/.eslintrc
    at Function.module.exports [as sync] (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config/config-file.js:416:38)
    at load (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config/config-file.js:435:24)
    at /Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config/config-file.js:338:28)
    at Object.load (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config/config-file.js:462:22)
    at loadConfig (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/Users/galenandrew/.nvm/versions/node/v4.3.1/lib/node_modules/eslint/lib/config.js:223:22)```

**Comment by ehis** [comment]
@galenandrew is this issue resolved?

**Comment by ehis** [comment]
Closing since no feedback. Probably resolved
